### PR TITLE
Feature/50 location

### PR DESCRIPTION
**Pull request by wenwenchenbosch**

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Need to check Readme Links (e.g. Link to vss-textclient broken) in several places

**Comment by wenwenchenbosch** [comment]
> Need to check Readme Links (e.g. Link to vss-textclient broken) in several places

done

**Comment by SebastianSchildt** [comment]
New dependecy https://pypi.org/project/gps/
Version 3.2.1 (or any other 
Source: https://gitlab.com/gpsd/gpsd/-/tree/release-3.21
License: BSD, see https://gitlab.com/gpsd/gpsd/-/blob/release-3.21/COPYING   

It is works with, as the feeder is an optional component

Can someody CQ @rohoet @phil-hei ?

**Comment by SebastianSchildt** [comment]
This mainly reorganiszes our examples and the testclient into the `clients` folder, making code reuse simpler. It also includes a new gps feeder publishing GPSd data to KUKSA.val

This works. Should be merged, so future PRs can be based on the cleaned up folder structure

**Review by SebastianSchildt — APPROVED** [review]

**Comment by rohoet** [comment]
> New dependecy https://pypi.org/project/gps/
> Version 3.2.1 (or any other
> Source: https://gitlab.com/gpsd/gpsd/-/tree/release-3.21
> License: BSD, see https://gitlab.com/gpsd/gpsd/-/blob/release-3.21/COPYING
> 
> It is works with, as the feeder is an optional component
> 
> Can someody CQ @rohoet @phil-hei ?

Does gpsd require any third party software or is it independent? It seems to be a rather large dependency and I could not figure out further dependencies at first glance - confirmation is of course better though :-)

**Comment by SebastianSchildt** [comment]
@rohoet, you commented somewhere here, but I only saw it via mail, I can not see it on the webpage

You sait: . 

`Does gpsd require any third party software or is it independent? `
As we are only using the python bindings https://gitlab.com/gpsd/gpsd/-/tree/release-3.21/gps  we do not even need "gpsd" (the compiled C part) as such, because the python bindings talk to gpsd or potentially another compatible server using  (network) sockets.  

As far as I could see (did not got to all gpsd python code files line-by-line). the python bindings themselves only use standard python libs.

**Comment by rohoet** [comment]
> @rohoet, you commented somewhere here, but I only saw it via mail, I can not see it on the webpage
> 
> You sait: .
> 
> `Does gpsd require any third party software or is it independent? `
> As we are only using the python bindings https://gitlab.com/gpsd/gpsd/-/tree/release-3.21/gps we do not even need "gpsd" (the compiled C part) as such, because the python bindings talk to gpsd or potentially another compatible server using (network) sockets.
> 
> As far as I could see (did not got to all gpsd python code files line-by-line). the python bindings themselves only use standard python libs.

I just noticed the works-with indication so my comment was obsolete ;-)

**Review by rohoet — APPROVED** [review]
LGTM

**Comment by rohoet** [comment]
> New dependecy https://pypi.org/project/gps/
> Version 3.2.1 (or any other
> Source: https://gitlab.com/gpsd/gpsd/-/tree/release-3.21
> License: BSD, see https://gitlab.com/gpsd/gpsd/-/blob/release-3.21/COPYING
> 
> It is works with, as the feeder is an optional component
> 
> Can someody CQ @rohoet @phil-hei ?

CQ filed.

**Pull request merged**
