### PR TITLE
Add deprecation/migration note to Databroker

### PR DESCRIPTION
**Pull request by erikbosch**
Intended workflow:

- Merge this one
- Then tag repo with 0.4.3
- Then trigger ghcr containers for 0.4.3

After that we may consider removing Databroker code from this repo

*Note: This one shall maybe not be merged until we have performed sufficient testing on new repo, so that we can*
*release 0.4.4 in new repo at about the same time*

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
So maybe workflow should be "release in in new Repo first", then do the steps above?

**Comment by erikbosch** [comment]
> So maybe workflow should be "release in in new Repo first", then do the steps above?

Yes, that works as well and is less ambiguous

**Comment by erikbosch** [comment]
@SebastianSchildt - a pre-release of https://github.com/eclipse-kuksa/kuksa-databroker/releases/tag/0.4.4 now exists, so now I think this one is ready for approval and merge

**Comment by SebastianSchildt** [comment]
Not sure, there was a very scary NOTICE.,d with lots of bullshit attached to the releases. I was thinking deleting the release, but for now just remove the file (I have a local copy). We should investigate where that came from

**Review by SebastianSchildt — CHANGES_REQUESTED** [review]
.

**Comment by SebastianSchildt** [comment]
I digged deeper on the Notice, it was just an super outdated file (that never made much sense anyway). So I "fixed" it here https://github.com/eclipse-kuksa/kuksa-databroker/pull/13 but please check @erikbosch

**Comment by erikbosch** [comment]
> .

So are there any changes required in this PR/repo @SebastianSchildt?

**Review by SebastianSchildt — COMMENTED** [review]
Hi @erikbosch . Not really. Yesterday I was just not sure, this is a bigger thing that will block us some time. So I think not. The release is "fixed", the other PR, we should merge sime time after.

So this one COULD be merged, I did not actually test /check the changes here so I can not "approve" just yet

**Comment by erikbosch** [comment]
I have done a smoke test, starting databroker+dtabroker-cli and made sure they can talk to each other

**Review by SebastianSchildt — APPROVED** [review]
lgtm 🦒

**Pull request merged**
