### PR TITLE
Throw an error while reading unset values.

### PR DESCRIPTION
**Pull request by nayakned**
getValue on values not explicitly set should throw an error.

This should implement #297

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Tested with websocket and GRPC. Seems to work fine.
I wonder whether we should send another code than 400, but did not find a fitting one on a first glance (definitely not 404, because we use that to indicate the path is no valid). 400 is fine, but generic, and probably used more often.  I am wondering if it is easier if client can easily detect this special condition (nothing published yet) by just looking at the number

**Comment by SebastianSchildt** [comment]
Hmm wrt to 404 it seems VISS suggests it https://www.w3.org/TR/viss2-transport/#status-codes

**Comment by nayakned** [comment]
@SebastianSchildt This exception will also be thrown when a entire branch is being read, and even if one of the leaves has not been previously set. E.g. getValue on Vehicle.OBD.* will throw this error as soon as it encounters the first datapoint that hasnt been set.

Would that be ok?

**Comment by SebastianSchildt** [comment]
> @SebastianSchildt This exception will also be thrown when a entire branch is being read, and even if one of the leaves has not been previously set. E.g. getValue on Vehicle.OBD.* will throw this error as soon as it encounters the first datapoint that hasnt been set.
> 
> Would that be ok?

Guess that is ok. We never promised anything regarding that behaviour (it seems to be one of this "atomic or not" discussions. Most common usecase is querying single values, and if you DO query a branch, most likely it is required/expected to get all subelements to be useful at all (e.g. GPS position), so I think it is toally acceptable to bail out if not all of the requested data can be provided.

**Pull request merged**
