### PR TITLE
Improve Cucumber based integration tests

### PR DESCRIPTION
**Pull request by sophokles73**
Added support for interacting with the Databroker using TLS.
Added scenarios for testing reading/writing of target values.
Omit Databroker integration test code from coverage report

### CODE REVIEW

**Comment by lukasmittag** [comment]
Nice work. I'm currently looking into adding integration test for permission checking too and therefore also changed a bit of the wolrd mod.rs but this PR looks good for now.

**Comment by lukasmittag** [comment]
just check the lint errors :) @sophokles73

**Comment by sophokles73** [comment]
> I'm currently looking into adding integration test for permission checking to

That's good to know, I will then leave that to you ... :-)

**Review by lukasmittag — APPROVED** [review]
LGTM

**Pull request merged**
