### PR TITLE
Give kuksa-client ability to encode array values to set and get them

### PR DESCRIPTION
**Pull request by lukasmittag**
Example: 
```
setValue  Vehicle.Cabin.SeatPosCount [1, 2, 3]
```
```
getValue Vehicle.Cabin.SeatPosCount
{
    "path": "Vehicle.Cabin.SeatPosCount",
    "value": {
        "value": {
            "values": [
                "1",
                "2",
                "3"
            ]
        },
        "timestamp": "2023-05-04T08:01:32.326616+00:00"
    }
}
```

### CODE REVIEW

**Comment by lukasmittag** [comment]
While testing myself found the issue that setting with 12,24,35 would not work because then it would set 1,2,2,4,3,5

**Comment by erikbosch** [comment]
Two observations:

It seems quotes are required (for me at least) if including blanks. Do we possibly have (or need) some documentation giving examples on how you specify different values on the command line.
```
Test Client> setValue Vehicle.Cabin.SeatPosCount [1, 2, 3]
usage: setValue [-h] [-a ATTRIBUTE] Path Value
setValue: error: unrecognized arguments: 2, 3]
Test Client> setValue Vehicle.Cabin.SeatPosCount "[1, 2, 3]"
OK
```

Secondly it seems that we cannot set an empty array:

```
Test Client> setValue Vehicle.Cabin.SeatPosCount []
{
    "error": "ValueError in casting the value."
}
```

**Comment by lukasmittag** [comment]
This is documented in the README. If you want to use spaces between elements [1,2,3] would work. This is an old issue/problem. Maybe we could fix that too some time.

**Comment by lukasmittag** [comment]
> Two observations:
> 
> It seems quotes are required (for me at least) if including blanks. Do we possibly have (or need) some documentation giving examples on how you specify different values on the command line.
> 
> ```
> Test Client> setValue Vehicle.Cabin.SeatPosCount [1, 2, 3]
> usage: setValue [-h] [-a ATTRIBUTE] Path Value
> setValue: error: unrecognized arguments: 2, 3]
> Test Client> setValue Vehicle.Cabin.SeatPosCount "[1, 2, 3]"
> OK
> ```
> 
> Secondly it seems that we cannot set an empty array:
> 
> ```
> Test Client> setValue Vehicle.Cabin.SeatPosCount []
> {
>     "error": "ValueError in casting the value."
> }
> ```

To the second comment. Is this even a use case? Do we want to support this? But yes I see that there is some improvement there. Will try something out.

**Comment by lukasmittag** [comment]
The newest commit allows the ability to set arrays with spaces like [1, 2, 3] therefore what now is possible to is setValue Vehicle.Speed 1 1 1 and this gets an 
```
{
    "error": "ValueError in casting the value."
}
```
I think this is fine. Opinions?

**Comment by SebastianSchildt** [comment]
From reading the comments, seems fine to me

@erikbosch Do you consider this done now?

**Comment by lukasmittag** [comment]
Not done. 
Test Client> setValue Vehicle.OBD.DTCList ["hh","jj"]
OK

 

Test Client> getValue Vehicle.OBD.DTCList
{
    "path": "Vehicle.OBD.DTCList",
    "value": {
        "value": {
            "values": [
                "\"hh\"",
                "\"jj\""
            ]
        },
        "timestamp": "2023-05-12T09:36:24.159561+00:00"
    }
}
it includes " " into the array values

**Comment by lukasmittag** [comment]
Needs a rework of trailing whitespaces too
Test Client> setValue Vehicle.Powertrain.FuelSystem.SupportedFuel [E5_95, E10_95]
{
    "error": {},
    "errors": [
        {
            "path": "Vehicle.Powertrain.FuelSystem.SupportedFuel",
            "error": {
                "code": 400,
                "reason": "value out of bounds",
                "message": "given value exceeds type's boundaries"
            }
        }
    ]
}

Test Client> setValue Vehicle.Powertrain.FuelSystem.SupportedFuel [E5_95,E10_95]
OK

Test Client> getValue Vehicle.Powertrain.FuelSystem.SupportedFuel
{
    "path": "Vehicle.Powertrain.FuelSystem.SupportedFuel",
    "value": {
        "value": {
            "values": [
                "E5_95",
                "E10_95"
            ]
        },
        "timestamp": "2023-05-12T10:14:42.818985+00:00"
    }
}

**Review by SebastianSchildt — APPROVED** [review]
lgtm 🌵

**Pull request merged**
