### PR TITLE
Fix bash dependency

### PR DESCRIPTION
**Pull request by d-s-e**
fixes https://github.com/eclipse/kuksa.val/issues/616

### CODE REVIEW

**Comment by erikbosch** [comment]
What tests have you performed?

I get an error when trying to run `./genCerts.sh ` after your fix. With bash it works. Are possibly more changes needed in the file to avoid the bash dependency?

```
erik@debian3:~/kuksa.val/kuksa_certificates$ ./genCerts.sh 
./genCerts.sh: 27: Syntax error: "(" unexpected
```

**Comment by erikbosch** [comment]
The newly added pre-commit check also complains, there seems to be a trailing space in one of the files. See https://github.com/eclipse/kuksa.val/blob/master/README.md#pre-commit-set-up on info how to set up pre-commit checks locally

**Comment by SebastianSchildt** [comment]
Haven't checked, but maybe try a space before the " (", not sure POSIX has something to say about it.... When going the vanilla "sh" (which in your system might actually be anything), at least try with busybox, as that is at least a "likely" target ot be encountered in embedded environments

**Comment by d-s-e** [comment]
Sorry, I didn't see that.
Will fix this.

**Comment by d-s-e** [comment]
should work now.

**Comment by SebastianSchildt** [comment]
I have been using `echo` all my life, and was wondering if it is really clever going for printf in shell here. Spoiler alert: It is. I've been **deep** in the rabbit hole just now, and wanted to share: https://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo/65819#65819

**Review by erikbosch — APPROVED** [review]
I ran both scripts locally on my Debian VM, they worked and no regressions.

@SebastianSchildt - I have no problems if this PR gets merged before v0.4.0, it does not affect any release artifacts apart from the source zip

**Pull request merged**
