### PR TITLE
Add Jenkjinsfile for automated builds

### PR DESCRIPTION
**Pull request by SebastianSchildt**
This adds a Jenkinsfile for automated builds

No functionality/code is changed so it should be ok to merge @rohoet @daschubert

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Argh, can somebody help me to see what is wrong. Both commits have signed-off, don't they?

**Comment by rohoet** [comment]
The sign-off message appears to be ok, but the eca validation fails at the second commit with 
> Anonymous (sebastian@****.de) is not covered by the necessary legal agreements in order to proceed.

Did you use a different git configuration for the second commit?

**Comment by SebastianSchildt** [comment]
I see the problem :-( Will try to repair.... "Author" is different.... Was from another computer

**Comment by SebastianSchildt** [comment]
Repaired!

**Comment by rohoet** [comment]
Thank you, Sebastian! LGTM

**Pull request merged**
