### PR TITLE
141 test client version number

### PR DESCRIPTION
**Pull request by wenwenchenbosch**
solve #143

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
I would suggest removing the logo, as it is very large, an probably a little annyoing if you see it every time starting the testclient, especially since it sort of defeats the purpose of  seeing the verison number,as it easily scrolls out of view
grafik

(or it can somehwo be made MUCH smaller, (i.e. no "KUKSA" text and version beside the "graphic")

**Comment by wenwenchenbosch** [comment]
@SebastianSchildt  now the logo should be smaller.

**Review by SebastianSchildt — APPROVED** [review]
Still not a fan of the logo, but want the feature anyway 🍰

**Comment by wenwenchenbosch** [comment]
@SebastianSchildt also no merge commit? no merge commit very fatal

**Pull request merged**
