### PR TITLE
Improve access check implementation

### PR DESCRIPTION
**Pull request by wenwenchenbosch**
redundant write access check is removed now, to move the read access check from VssDatabase is more work to do, because all children path should also be checked:
https://github.com/eclipse/kuksa.val/blob/master/src/VssDatabase.cpp#L556

But I think we should continue, because you can see, `setSignal()` now has no dependencies to `wsChannel` any more. Much more clean. @SebastianSchildt what do you think?

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
I like the idea.

For get, I think the "getSignal" in Database should become  "primitive" and not deal with multiple values, that should probably be handled outside. (Maybe employing some "helpers" in VSSDatabase, to recursively find childrens...)

**Comment by SebastianSchildt** [comment]
I think this is not good, as it makes branch reads without "full access rights" useless

```

Test Client> getValue Vehicle.VehicleIdentification
{
    "action": "get", 
    "error": {
        "message": "No read access to Vehicle.VehicleIdentification", 
        "number": 403, 
        "reason": "Forbidden"
    }, 
    "requestId": "de3b70da-f909-4250-9f3d-5b9a1337f1e7", 
    "timestamp": 1619618049987
}

Test Client> getValue Vehicle.OBD
{
    "action": "get", 
    "requestId": "95cefcb0-d790-46a8-8c16-e8c2b115c7f7", 
    "timestamp": "1619617694719", 
    "value": [
        {
            "Vehicle.OBD.Speed": "200"
        }
    ], 
    "warning": "No read access to [ Vehicle.OBD.AbsoluteLoad,Vehicle.OBD.AcceleratorPositionD,Vehicle.OBD.AcceleratorPositionE,Vehicle.OBD.AcceleratorPositionF,Vehicle.OBD.AirStatus,Vehicle.OBD.AmbientAirTemperature,Vehicle.OBD.AuxInputStatus,Vehicle.OBD.BarometricPressure,Vehicle.OBD.Catalyst.Bank1.Temperature1,Vehicle.OBD.Catalyst.Bank1.Temperature2,Vehicle.OBD.Catalyst.Bank2.Temperature1,Vehicle.OBD.Catalyst.Bank2.Temperature2,Vehicle.OBD.CommandedEGR,Vehicle.OBD.CommandedEVAP,Vehicle.OBD.CommandedEquivalenceRatio,Vehicle.OBD.ControlModuleVoltage,Vehicle.OBD.CoolantTemperature,Vehicle.OBD.DTCList,Vehicle.OBD.DistanceSinceDTCClear,Vehicle.OBD.DistanceWithMIL,Vehicle.OBD.DriveCycleStatus.DTCCount,Vehicle.OBD.DriveCycleStatus.IgnitionType,Vehicle.OBD.DriveCycleStatus.MIL,Vehicle.OBD.EGRError,Vehicle.OBD.EVAPVaporPressure,Vehicle.OBD.EVAPVaporPressureAbsolute,Vehicle.OBD.EVAPVaporPressureAlternate,Vehicle.OBD.EngineLoad,Vehicle.OBD.EngineSpeed,Vehicle.OBD.EthanolPercent,Vehicle.OBD.FreezeDTC,Vehicle.OBD.FuelInjectionTiming,Vehicle.OBD.FuelLevel,Vehicle.OBD.FuelPressure,Vehicle.OBD.FuelRailPressureAbsolute,Vehicle.OBD.FuelRailPressureDirect,Vehicle.OBD.FuelRailPressureVac,Vehicle.OBD.FuelRate,Vehicle.OBD.FuelStatus,Vehicle.OBD.FuelType,Vehicle.OBD.HybridBatteryRemaining,Vehicle.OBD.IntakeTemp,Vehicle.OBD.LongTermFuelTrim1,Vehicle.OBD.LongTermFuelTrim2,Vehicle.OBD.LongTermO2Trim1,Vehicle.OBD.LongTermO2Trim2,Vehicle.OBD.MAF,Vehicle.OBD.MAP,Vehicle.OBD.MaxMAF,Vehicle.OBD.O2.Bank1.Sensor1.Voltage,Vehicle.OBD.O2.Bank1.Sensor2.Voltage,Vehicle.OBD.O2.Bank1.Sensor3.Voltage,Vehicle.OBD.O2.Bank1.Sensor4.Voltage,Vehicle.OBD.O2.Bank2.Sensor1.Voltage,Vehicle.OBD.O2.Bank2.Sensor2.Voltage,Vehicle.OBD.O2.Bank2.Sensor3.Voltage,Vehicle.OBD.O2.Bank2.Sensor4.Voltage,Vehicle.OBD.O2WR.Sensor1.Current,Vehicle.OBD.O2WR.Sensor1.Voltage,Vehicle.OBD.O2WR.Sensor2.Current,Vehicle.OBD.O2WR.Sensor2.Voltage,Vehicle.OBD.O2WR.Sensor3.Current,Vehicle.OBD.O2WR.Sensor3.Voltage,Vehicle.OBD.O2WR.Sensor4.Current,Vehicle.OBD.O2WR.Sensor4.Voltage,Vehicle.OBD.O2WR.Sensor5.Current,Vehicle.OBD.O2WR.Sensor5.Voltage,Vehicle.OBD.O2WR.Sensor6.Current,Vehicle.OBD.O2WR.Sensor6.Voltage,Vehicle.OBD.O2WR.Sensor7.Current,Vehicle.OBD.O2WR.Sensor7.Voltage,Vehicle.OBD.O2WR.Sensor8.Current,Vehicle.OBD.O2WR.Sensor8.Voltage,Vehicle.OBD.OilTemperature,Vehicle.OBD.PidsA,Vehicle.OBD.PidsB,Vehicle.OBD.PidsC,Vehicle.OBD.RelativeAcceleratorPosition,Vehicle.OBD.RelativeThrottlePosition,Vehicle.OBD.RunTime,Vehicle.OBD.RunTimeMIL,Vehicle.OBD.ShortTermFuelTrim1,Vehicle.OBD.ShortTermFuelTrim2,Vehicle.OBD.ShortTermO2Trim1,Vehicle.OBD.ShortTermO2Trim2,Vehicle.OBD.Status.DTCCount,Vehicle.OBD.Status.IgnitionType,Vehicle.OBD.Status.MIL,Vehicle.OBD.ThrottleActuator,Vehicle.OBD.ThrottlePosition,Vehicle.OBD.ThrottlePositionB,Vehicle.OBD.ThrottlePositionC,Vehicle.OBD.TimeSinceDTCCleared,Vehicle.OBD.TimingAdvance,Vehicle.OBD.WarmupsSinceDTCClear ]"
}
```

Either the semantics should be, "return just what is visible (i.e. remove the warning, which is not standard compliant anyway), or give a 404, if we think everything needs to be accessible

If defined, this should follow V2 spec

**Comment by SebastianSchildt** [comment]
Found this
https://raw.githack.com/w3c/automotive/gh-pages/spec/VISSv2_Core.html#error-handling

> A request addressing multiple nodes may address both valid nodes, and invalid nodes. The latter case shall lead to a Not found error response message part that contains information about which node, or nodes, that are invalid. The error response shall not contain data from any of the validly addressed nodes. 

While it says "Not found", it still would point toward the "do not return anything" when not having all access rights.

**Comment by wenwenchenbosch** [comment]
> Found this
> https://raw.githack.com/w3c/automotive/gh-pages/spec/VISSv2_Core.html#error-handling
> 
> > A request addressing multiple nodes may address both valid nodes, and invalid nodes. The latter case shall lead to a Not found error response message part that contains information about which node, or nodes, that are invalid. The error response shall not contain data from any of the validly addressed nodes.
> 
> While it says "Not found", it still would point toward the "do not return anything" when not having all access rights.

ok, I will remove the feature. I thought it may be useful

**Comment by SebastianSchildt** [comment]
I asked, so the expected behavior for querying multiple leafs is
 - check desired access level for all leafs
 - if _any_ leaf can not be accessed, return a 403/forbidden for the complete query
 - do not return a "partial" subset of addressed paths

**Comment by wenwenchenbosch** [comment]
>     * do not return a "partial" subset of addressed paths

@SebastianSchildt  done

**Review by SebastianSchildt — APPROVED** [review]

**Pull request merged**
